import { readFile, writeFile, mkdir } from 'node:fs/promises';
await mkdir('src/lib/abi', { recursive: true });
const names = ['Rung', 'StageEscrow', 'RetroRound'];
const exportNames = {};
for (const name of names) {
  const { abi } = JSON.parse(await readFile(`out/${name}.sol/${name}.json`, 'utf8'));
  const exportName = name[0].toLowerCase() + name.slice(1) + 'Abi';
  exportNames[name] = exportName;
  await writeFile(`src/lib/abi/${name}.ts`, `// Generated by pnpm contracts.\nexport const ${exportName} = ${JSON.stringify(abi)} as const;\n`);
}
await writeFile('src/lib/abi/index.ts',
  `// Generated by pnpm contracts.\n` +
  names.map(n => `export { ${exportNames[n]} } from './${n}';`).join('\n') + '\n');
